---
http_interactions:
- request:
    method: post
    uri: http://unix/v1.4/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Cmd":["true"],"Image":"base"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        U2F0LCAxOSBPY3QgMjAxMyAxNzoxOToxNyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"c0f60ea1d06e"}'
    http_version:
  recorded_at: Sat, 19 Oct 2013 17:19:17 GMT
- request:
    method: post
    uri: http://unix/v1.4/commit?container=c0f60ea1
    body:
      encoding: UTF-8
      string: ! '{"Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        U2F0LCAxOSBPY3QgMjAxMyAxNzoxOToxNyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"522fa6622ec5"}'
    http_version:
  recorded_at: Sat, 19 Oct 2013 17:19:17 GMT
- request:
    method: post
    uri: http://unix/v1.4/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Image":"522fa6622ec5"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MjE=
      !binary "RGF0ZQ==":
      - !binary |-
        U2F0LCAxOSBPY3QgMjAxMyAxNzoxOToxNyBHTVQ=
    body:
      encoding: US-ASCII
      string: ! '{"Id":"40686d742482"}'
    http_version:
  recorded_at: Sat, 19 Oct 2013 17:19:17 GMT
- request:
    method: post
    uri: http://unix/v1.4/containers/40686d742482/start
    body:
      encoding: UTF-8
      string: ! '{}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        dGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOA==
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        MA==
      !binary "RGF0ZQ==":
      - !binary |-
        U2F0LCAxOSBPY3QgMjAxMyAxNzoxOToxNyBHTVQ=
    body:
      encoding: US-ASCII
      string: ''
    http_version:
  recorded_at: Sat, 19 Oct 2013 17:19:17 GMT
- request:
    method: post
    uri: http://unix/v1.4/containers/40686d742482/attach?stdout=true&stream=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.6.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vdm5kLmRvY2tlci5yYXctc3RyZWFt
    body:
      encoding: US-ASCII
      string: ! '/

'
    http_version:
  recorded_at: Sat, 19 Oct 2013 17:19:17 GMT
recorded_with: VCR 2.6.0
